# Generated by Django 3.1.6 on 2021-02-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0003_courses_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
